### ISSUE TITLE
Webpack Monitor doesn´t know create routes

### ISSUE THREAD

**Issue by IvanRodriCalleja** [webpackmonitor/webpackmonitor#106]
Hi 

I am trying to configure webpack-monitor to have a outpul tile `target: '../reports/monitor/monitor-stats.json'`

When i execute the build, i get this error. ENOENT: no such file or directory, mkdir 'C:\git\ReactWebpackBoilerplate\reporter\monitor'

Actually i am using Webpack 4 with webpack-monitor: 1.0.14.

Is this working correctly?

**Comment by MrEfbiaye** [comment]
I have almost the same problem and I do not have a miracle solution: /

I need to get the project I'm using (available on GitHub) running under Docker.
So I created a Dockerfile that worked before the project was updated with Web Monitor.

When I download the project on my Windows machine and I execute the commands one by one it works: D

When I do exactly the same thing under Linux (through the dockerfile and because of that, in a container), I get the following error message:

/usr/projet/starter/node_modules/webpack/bin/webpack.js:348
                        throw err;
                        ^

Error: ENOENT: no such file or directory, mkdir '/usr/projet/starter/reports/webpack-monitor'
    at Object.fs.mkdirSync (fs.js:840:3)
    at MonitorStats.apply (/usr/projet/starter/node_modules/webpack-monitor/monitor.js:83:10)
    at Compiler.apply (/usr/projet/starter/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/usr/projet/starter/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/usr/projet/starter/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/usr/projet/starter/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/usr/projet/starter/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/usr/projet/starter/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm [......]
[.....]
[.....] 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-03T09_36_38_654Z-debug.log

What can I do to solve the problem?

**Comment by tenretC** [comment]
Same issue for me,
When I configured webpack-monitor to have an output file here : `target: helpers.root("reports/webpack-monitor/stats.json")`

When i do npm start, i get this error : Error: ENOENT: no such file or directory, mkdir 'C:\LocalData\DEV\GIT\stark\starter\reports\webpack-monitor'

I'm also using the 1.0.14 version.

I've seen that in my node_modules/webpack-monitor, the mkdirp dependency is missing.
