### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: undefined:412:2: selector missing

### ISSUE THREAD

**Issue by jamalsoueidan** [webpackmonitor/webpackmonitor#109]
Hello,

I'm getting this error when using WebpackMonitor.

I'm using node 8.11.3 and webpack 4.x.x

> npm run build

> unified-boilerplate@5.0.0 build C:\Users\911161\reactjs\boilerplate
> webpack --mode production --config webpack/production.js

(node:22280) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
DEPRECATION WARNING on line 3, column 10 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

(node:22280) UnhandledPromiseRejectionWarning: Error: undefined:412:2: selector missing
    at error (C:\Users\911161\reactjs\boilerplate\node_modules\css\lib\parse\index.js:62:15)
    at rule (C:\Users\911161\reactjs\boilerplate\node_modules\css\lib\parse\index.js:555:22)
    at rules (C:\Users\911161\reactjs\boilerplate\node_modules\css\lib\parse\index.js:118:70)
    at stylesheet (C:\Users\911161\reactjs\boilerplate\node_modules\css\lib\parse\index.js:81:21)
    at module.exports (C:\Users\911161\reactjs\boilerplate\node_modules\css\lib\parse\index.js:565:20)
    at rework (C:\Users\911161\reactjs\boilerplate\node_modules\rework\index.js:27:21)
    at CssTreeWalker.beginReading (C:\Users\911161\reactjs\boilerplate\node_modules\purify-css\lib\purifycss.js:568:24)
    at purify (C:\Users\911161\reactjs\boilerplate\node_modules\purify-css\lib\purifycss.js:1009:10)
    at compiler.plugin (C:\Users\911161\reactjs\boilerplate\node_modules\webpack-monitor\monitor.js:74:24)
    at _err1 (eval at create (C:\Users\911161\reactjs\boilerplate\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:17:1)
    at compiler.plugin (C:\Users\911161\reactjs\boilerplate\node_modules\webpack-monitor\monitor.js:49:7)
    at _err0 (eval at create (C:\Users\911161\reactjs\boilerplate\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
    at Promise.resolve.then.then.then.then.then.then.then.then.catch.then.then.then (C:\Users\911161\reactjs\boilerplate\node_modules\html-webpack-plugin\index.js:224:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:22280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by roachjc** [comment]
Hey Jamal. Webpack Monitor doesn't support Webpack 4 and is currently unmaintained. Recommend checking out https://github.com/FormidableLabs/webpack-dashboard as an alternative. Good luck 😄

**Comment by jamalsoueidan** [comment]
@roachjc  Thank you 👍 

...closing
