### ISSUE TITLE
error when used with next.js

### ISSUE THREAD

**Issue by thanhtoan1196** [webpackmonitor/webpackmonitor#117]
error when used with next.js

```
Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at Function.listen (/Users/toan/Desktop/frontend/story-react/node_modules/express/lib/application.js:618:24)
    at module.exports (/Users/toan/Desktop/frontend/story-react/node_modules/webpack-monitor/utils/server.js:24:7)
    at /Users/toan/Desktop/frontend/story-react/node_modules/webpack-monitor/monitor.js:127:34
    at /Users/toan/Desktop/frontend/story-react/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:154:23)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8081
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nickensoul** [comment]
Have you tried to change the `port` option?
```js
new WebpackMonitor({
  port: 3232,
})
```
