### ISSUE TITLE
Error happened

### ISSUE THREAD

**Issue by zhaosaisai** [webpackmonitor/webpackmonitor#47]
**environments**

```bash
node: v8.3.0
global webpack:  v1.15.0
dev webpack: 2.7.0
```

**my config**

```javascript
const WebpackMonitorConfig = new WebpackMonitor({
    capture: true,
    launch: true,
    port: 3030
})
```

**error in terminal**

```bash
yarn run v0.27.5
$ node server.js
The server is listening on 8088
/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack-monitor/utils/parser.js:21
      modules: chunk.modules.map(module => ({
                            ^

TypeError: Cannot read property 'map' of undefined
    at chunks.stats.chunks.map.chunk (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack-monitor/utils/parser.js:21:29)
    at Array.map (<anonymous>)
    at module.exports (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack-monitor/utils/parser.js:18:26)
    at Compiler.compiler.plugin (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack-monitor/monitor.js:87:24)
    at Compiler.applyPlugins (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack/lib/Compiler.js:98:16)
    at /Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack/lib/Compiler.js:73:18
    at Compiler.emitRecords (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack/lib/Compiler.js:367:37)
    at /Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack/lib/Compiler.js:56:19
    at /Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack/lib/Compiler.js:360:11
    at next (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack/lib/Compiler.js:357:8)
    at Compiler.<anonymous> (/Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/webpack/lib/Compiler.js:352:14)
    at /Users/pavoooo/Documents/Pavoooo/job/report-form/node_modules/async/dist/async.js:421:16
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by roachjc** [comment]
Hi @2json thanks for submitting an issue! Working on this today! Will revert when done!

**Comment by roachjc** [comment]
So couple of things this could have been. 
- There's a chunk with no modules. Not something I had anticipated, but should now be fixed. Update is on npm too. LMK if you get other issues! Sorry 😬
- Different version of webpack might be generating stats of different structure. Webpack Monitor should be compatible with v2+. So if your global install is running the build then that might be the problem.

**Comment by zhaosaisai** [comment]
@roachjc Thanks for your job! I have upgraded my global webpack to 2.7.0 and reinstalled the webpack-monitor from npm. and the error disappeard! thanks for your good job and you can close the issue!
