### ISSUE TITLE
throw error on port 8081 when editing code

### ISSUE THREAD

**Issue by melunar** [webpackmonitor/webpackmonitor#78]
当我编译项目的时候, 没问题; 但是修改代码实时编译就报错了, 如下: 
all is good, bug when I change my code, something wrong happened: 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (E:\workspace\_project\VueCliLearn\node_modules\._express@4.16.2@express\lib\application.js:618:24)
    at module.exports (E:\workspace\_project\VueCliLearn\node_modules\._webpack-monitor@1.0.13@webpack-monitor\utils\server.js:24:7)
    at fs.writeFile (E:\workspace\_project\VueCliLearn\node_modules\._webpack-monitor@1.0.13@webpack-monitor\monitor.js:124:34)
    at E:\workspace\_project\VueCliLearn\node_modules\._graceful-fs@4.1.11@graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)

```

wating for u~~~, good plugin

**Comment by mbehzad** [comment]
Hi @melunar, it sounds like webpack-monitor is already running, or the `8081` port is used by another application.
For example if the webpack-monitor is in your webpack configuration which is used with webpack dev server then the wmp server will try to start each time something in your code changes and webpack rebuilds.
Please have a look at this two issues, they may be the same as yours:
[EADDRINUSE on compile #48](https://github.com/webpackmonitor/webpackmonitor/issues/48)
[Support for hot reloading #69](https://github.com/webpackmonitor/webpackmonitor/issues/69)

**Comment by melunar** [comment]
@mbehzad thanks so much, and it is the same issues,,, maybe I shoule use the monitor just when my project build.
